"""Build consistent palette variants from the accepted PixelLab monster sheets."""

import colorsys
import json
from pathlib import Path

from PIL import Image


ROOT = Path('assets/enemies')
STATES = ('idle', 'walk', 'attack', 'block', 'hit', 'death')
VARIANTS = {
    'caveSlime': ('slime-cave', {'turquoise': 185, 'amber': 32}),
    'elderSlime': ('slime-cave', {'cobalt': 220, 'crimson': 350}),
    'ruffian': ('thornbriar-hollow', {'teal': 187, 'violet': 275}),
    'hedgeMage': ('thornbriar-hollow', {'teal': 185, 'burgundy': 340}),
    'lasher': ('thornbriar-hollow', {'navy': 220, 'rust': 12}),
}


def recolor_pixel(name, variant, hue, rgba):
    red, green, blue, alpha = rgba
    if alpha == 0:
        return rgba
    original_hue, saturation, value = colorsys.rgb_to_hsv(red / 255, green / 255, blue / 255)
    degrees = original_hue * 360
    target = None
    if name in ('caveSlime', 'elderSlime'):
        if 48 <= degrees <= 155 and saturation > 0.18:
            target = hue + (degrees - 85) * 0.22
            saturation = max(0.65, saturation)
    elif name == 'ruffian':
        if (degrees < 38 or degrees > 345) and saturation > 0.28 and value < 0.53:
            target = hue + min(degrees, 30) * 0.18
            saturation = max(0.4, saturation * 0.8)
    elif name == 'hedgeMage':
        if 255 <= degrees <= 320 and saturation > 0.35:
            target = 190 if variant == 'teal' else 25
            saturation = max(0.7, saturation)
        elif (degrees < 48 or degrees > 345) and saturation > 0.2 and value < 0.48:
            target = hue + min(degrees, 35) * 0.15
            saturation = max(0.38, saturation * 0.75)
    elif name == 'lasher':
        if 42 <= degrees <= 130 and saturation > 0.12 and value < 0.72:
            target = hue + (degrees - 65) * 0.1
            saturation = max(0.45, saturation)
        elif (degrees < 38 or degrees > 345) and saturation > 0.35 and value < 0.34:
            target = hue + min(degrees, 30) * 0.1
            saturation = max(0.35, saturation * 0.7)
    if target is None:
        return rgba
    if value < 0.32:
        value = min(1, value * 1.15)
    r, g, b = colorsys.hsv_to_rgb((target % 360) / 360, min(1, saturation), value)
    return round(r * 255), round(g * 255), round(b * 255), alpha


def build():
    catalog = ['// Generated by scripts/build-monster-variants.py.', 'export const MONSTER_VARIANT_SHEETS = {']
    for name, (area, variants) in VARIANTS.items():
        source = ROOT / area / name / 'reference-v2' / 'sheets'
        layout = json.loads((source / 'layout.json').read_text(encoding='utf-8'))
        for variant, hue in variants.items():
            sprite_id = name + variant.title()
            catalog.append(f'  {sprite_id}: [')
            for state in STATES:
                url = f'../assets/enemies/{area}/{name}/variants/{variant}/sheets/{state}.png'
                catalog.append(f"    new URL('{url}', import.meta.url).href,")
            catalog.append('  ],')
            output = ROOT / area / name / 'variants' / variant / 'sheets'
            output.mkdir(parents=True, exist_ok=True)
            for state in STATES:
                with Image.open(source / f'{state}.png') as sheet:
                    sheet = sheet.convert('RGBA')
                    colors = sheet.getcolors(sheet.width * sheet.height)
                    palette = {color: recolor_pixel(name, variant, hue, color) for _, color in colors}
                    sheet.putdata([palette[color] for color in sheet.getdata()])
                    sheet.save(output / f'{state}.png', optimize=True)
            metadata = {**layout, 'baseSprite': name, 'variant': variant,
                        'source': 'accepted PixelLab animation sheets with a consistent palette edit'}
            (output / 'layout.json').write_text(json.dumps(metadata, indent=2), encoding='utf-8')
            print(f'Built {name}/{variant}: six sheets')
    catalog.append('};')
    Path('data/monsterVariantSheets.js').write_text('\n'.join(catalog) + '\n', encoding='utf-8')


if __name__ == '__main__':
    build()
